# Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/hivehub?allowPublicKeyRetrieval=true&useSSL=false
db.username=root
db.password=mypass

# Connection Pool Settings
db.pool.maxPoolSize=10
db.pool.minIdle=5
db.pool.connectionTimeout=30000